### ISSUE TITLE
Date math

### ISSUE THREAD

**Issue by zyphlar** [dlabey/simple-linux-bash-rotating-backup-script#1]
It may never be a problem, but assuming that a month will have at least 28 days or a year 364 is way less certain than simply backing up on the 1st of the year / 1st of the month. http://infiniteundo.com/post/25509354022/more-falsehoods-programmers-believe-about-time-wisdom

**Comment by dlabey** [comment]
Hi, while I do not think our calendar system will ever have a month under 28 days, your concern is pragmatic. I'll fix this soon, thanks.

**Comment by zyphlar** [comment]
It's just a good habit. I just wrote my own script based on number of days
since last modified which is more basic but might be useful too; it's in my
github repos list.
